# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Landtracker
                                 A QGIS plugin
 Plugin to create and analyze route paths
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-23
        copyright            : (C) 2024 by asdf
        email                : asdf
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Landtracker class from file Landtracker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .land_tracker import Landtracker
    return Landtracker(iface)
